#!/usr/bin/env bash

# Deploy to github pages

STATUS="$(git status)"

if [[ $STATUS == *"nothing to commit"* ]]
then 
  git config --global user.email "ka210n8@gmail.com"
  git config --global user.name "CircleCI"
  git rm .gitignore
  git add public
  git commit -m "Remove .gitignore and add public to publish"
  git subtree push --prefix public origin gh-pages
  git reset HEAD~
  git checkout .gitignore
else 
  echo "Need clean working directory to publish"
fi
